services:
  web:
    image: python:3.9
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      gunicorn core.wsgi:application --bind 0.0.0.0:8000
      '
    ports:
      - "80:8000"
    networks:
      - app-network
  
  celery:
    image: python:3.9
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      pip install -r requirements.txt
      celery -A core worker -l DEBUG
      '
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
