services:
  web:
    image: python:3.7
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      gunicorn ashwa.wsgi:application --bind 0.0.0.0:8000
      '
    ports:
      - "8000:80"
    networks:
      - app-network
  
  celery:
    image: python:3.7
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      pip install -r requirements.txt
      celery -A core worker -l INFO
      '
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
